import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Navbar from "./components/navbar";
import { AuthProvider } from "./auth/AuthContext";
import DashboardPage from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudyXChange",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
